import type { CSSProperties } from "react";

export const s = {
  footer: { display: "flex", gap: 10, justifyContent: "flex-end" } satisfies CSSProperties,
  body: { padding: 24, display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  fileInput: { fontSize: 13, cursor: "pointer" } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--color-error, #d32f2f)" } satisfies CSSProperties,
  previewSection: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  trustNote: {
    padding: "10px 14px",
    borderRadius: 6,
    background: "var(--color-warning-bg, #fff8e1)",
    border: "1px solid var(--color-warning-border, #ffe082)",
    fontSize: 13,
    color: "var(--text-primary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  readonlyField: {
    padding: "7px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 13,
    color: "var(--text-primary)",
    minHeight: 32,
  } satisfies CSSProperties,
  empty: { color: "var(--text-muted)", fontStyle: "italic" } satisfies CSSProperties,
  bodyTextarea: {
    width: "100%",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    lineHeight: 1.6,
    padding: "10px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    resize: "vertical",
    boxSizing: "border-box",
  } satisfies CSSProperties,
  ignoredList: {
    margin: 0,
    paddingLeft: 18,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  ignoredItem: {
    fontSize: 12,
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
} as const;
